Repository dev-protocol/stakes.social, pull requests merged in 2020-04, with the labels that each got.

#5 feat: detect browser wallet
  packages/web/package.json
  packages/web/src/fixtures/wallet/hooks.ts
  packages/web/src/pages/index.tsx
  packages/web/src/types/window.d.ts
  yarn.lock
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#7 feat: add connected button
  packages/web/src/components/organisms/WalletConnectButton/index.tsx
  packages/web/src/fixtures/wallet/catch-path.ts
  packages/web/src/fixtures/wallet/hooks.ts
  packages/web/src/fixtures/wallet/utility.ts
  packages/web/src/pages/about.tsx
  packages/web/src/pages/index.tsx
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#107 fixed issue106
  packages/web/src/components/organisms/PossessionOutline/__snapshots__/index.spec.tsx.snap
  packages/web/src/components/organisms/PossessionOutline/index.tsx
  packages/web/src/components/organisms/PropertyCardList/PropertyCard.tsx
  packages/web/src/fixtures/utility/__mocks__/gql-hooks-wrapper.ts
  packages/web/src/fixtures/utility/gql-hooks-wrapper.ts
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#111 Update @font-family
  packages/web/src/assets/antd-custom.less
Labels: Priority: Medium, Type: Feature

#112 Responsive design: PropertyCard
  packages/web/src/components/organisms/PropertyCardList/PropertyCard.tsx
  packages/web/src/components/organisms/PropertyCardList/__snapshots__/index.spec.tsx.snap
Labels: Priority: Medium, Type: Feature

#128 Fix the amount of "Withdraw Staking Reward"
  packages/web/src/components/organisms/TransactionForm/index.tsx
  packages/web/src/fixtures/dev-kit/__mocks__/hooks.ts
  packages/web/src/fixtures/dev-kit/cache-path.ts
  packages/web/src/fixtures/dev-kit/client.ts
  packages/web/src/fixtures/dev-kit/hooks.spec.ts
  packages/web/src/fixtures/dev-kit/hooks.ts
Labels: Type: Bug
